### ISSUE TITLE
Unix shell build script or makefile

### ISSUE THREAD

**Issue by ATroubleshooter** [b3rendsh/msxdos2s#1]
Hello, @b3rendsh ! It's a feature request.

I tried to build you improved BEER DISK ROM firmware and it builds and works mostly fine. But it would be handy to have not only .bat file, but also a unix-shell building script.

Thank you.

**Comment by ATroubleshooter** [comment]
And, btw, a few messages are waiting for you on msx.org forums, would you please take a look at them?

**Comment by b3rendsh** [comment]
It is on the todo list to create a makefile, also for the msxdos 2.2 build and other modules.

**Comment by ATroubleshooter** [comment]
@b3rendsh 
I'm seeing a Makefile prepared at least for dev-32k code.
Closing this one.

Thank you!
